"""
Django settings for django_hf_ml project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(  
    DEBUG=(bool, False),  
    
)

# garante que o .env é lido
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Django  
SECRET_KEY = env('SECRET_KEY')  
DEBUG = env('DEBUG', default=False)  
ALLOWED_HOSTS = [h.strip() for h in env('ALLOWED_HOSTS', default='').split(',') if h.strip()]

# MongoDB
MONGO_URI = env('MONGO_URI')  
MONGO_DB_NAME = env('MONGO_DB_NAME', default='django_hf_ml')  
MONGO_COLLECTION = env('MONGO_COLLECTION', default='interactions')

# Static Files
STATIC_URL = 'static/'  
STATICFILES_DIRS = [BASE_DIR / 'app' / 'static']

# Sessions  
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'  
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 dias

# HF / Transformers
HF_MODEL = env('HF_MODEL', default='google/flan-t5-small')  
HF_TASK = env('HF_TASK', default='text2text-generation')  
HF_API_TOKEN = env('HF_API_TOKEN', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_hf_ml.urls'

TEMPLATES = [  
    {  
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  
        'DIRS': [BASE_DIR / 'app' / 'templates'],  
        'APP_DIRS': True,  
        'OPTIONS': {  
            'context_processors': [  
                'django.template.context_processors.debug',  
                'django.template.context_processors.request',  
                'django.contrib.auth.context_processors.auth',  
                'django.contrib.messages.context_processors.messages',  
            ],  
        },  
    },  
]  
WSGI_APPLICATION = 'django_hf_ml.wsgi.application'


# Segurança extra  
CSRF_TRUSTED_ORIGINS = [o.strip() for o in env('CSRF_TRUSTED_ORIGINS', default='').split(',') if o.strip()]


# Logging básico com sanitização simples  
LOGGING = {  
    'version': 1,  
    'disable_existing_loggers': False,  
    'filters': {},  
    'formatters': {  
        'standard': {'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'},  
    },  
    'handlers': {  
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'}  
    },  
    'loggers': {  
        'django': {'handlers': ['console'], 'level': 'INFO'},  
        'app': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},  
    }  
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'app' / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
